### ISSUE TITLE
drop error for missing `crown.position` when `dead.crown.position` is recorded

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#103]

**Comment by teixeirak** [comment]
@ValentineHerr , please see the logic for this in issue #102. We'll have some other coding fixes in that issue to do later, but for now we will remove a lot of field checks by changing this from an error to a warning.

**Comment by teixeirak** [comment]
@ValentineHerr , it would be helpful if you could get to this today because Katherina is going out to the field tomorrow.

**Comment by ValentineHerr** [comment]
@FYI, the CI is failing for unrelated issue (some package update), trying to fix now.

**Comment by teixeirak** [comment]
Okay. I just pushed some updates to the data.

**Comment by ValentineHerr** [comment]
okay the CI has been fixed and the report is updated according to this issue

**Comment by ValentineHerr** [comment]
CI is triggered again with your last push

**Comment by teixeirak** [comment]
@ValentineHerr , it looks like something went wrong with CI when I pushed the new data: 

<img width="923" alt="image" src="https://user-images.githubusercontent.com/6355854/212322601-a993ba6e-aac2-48ec-a82c-366dd44e9520.png">

I don't think the updated reports capture the work Katherina has done.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr ! I didn't know that trick. I got it to run, but the results didn't change. I'm not sure if I put the file in the right place....

**Comment by ValentineHerr** [comment]
You want to update [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/raw_data/FFF_excel/SCBI%20Mortality%20field%20fixes%202022.xlsx) but I did it on my local machine and nothing got updated either...
 What was fixed in that file? Is it possible the wrong form was used in FFF? If not, could it be that what was edited did not impact the error and warning detections?

**Comment by teixeirak** [comment]
@ValentineHerr , I previously updated the wrong file, which would have been part of the problem. I tried again with a fresh download. It seems now there's some error in generating reports:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/6355854/212358587-1602f17a-56cf-4bad-a51c-641db09bcdfa.png">

**Comment by ValentineHerr** [comment]
hmmm, I think it is because of this situation of duplicated records... I wrote the script so it would generate an error when there is no obvious decision to make about some duplicated records.... Here, there are 2 non NA dbh measurement, 0 and 275. You can delete the wrong row or update on of the values and hopefully that will fix the error

![image](https://user-images.githubusercontent.com/19673377/212360277-de3c85c1-b30e-4ca1-876d-e939a3057cf8.png)
