### ISSUE TITLE
Fix issue with coordinates of trees that generates duplicates in FFF

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#25]
opening a separate issue from #21.

The issues with Qx and Qy seems to come from the data that is loaded in FFF. @jess-shue, did you change the data in FFF? It looks like Qx and Qy were changed to global coordinates in the last few submissions.
I know in the data I gave you there were a few local coordinates that were wrong (>20) but I don't thins that it was this many.

@teixeirak, 
Those duplicate trees with different Qx and Qy are in the Excel file of the FFF, and it looks like they were visited twice, but the stuff recorded is not always consistent.
Here is an example:
![image](https://user-images.githubusercontent.com/19673377/124359186-e1649a00-dbf1-11eb-8715-5e05ba52afb4.png)

**Comment by teixeirak** [comment]
For double-censused trees: 
- if one record has no errors/warning and the other has errors/warnings, please discard the one without errors/warning. 
- if neither have errors, select one at random
- if both have errors/warning, please flag for manual review. Whoever reviews should fix one, no need to fix both

**Comment by jess-shue** [comment]
@ValentineHerr  I can't tell from your screenshot, but if you can confirm what version those two were submitted from that might help. If row 6021 was submitted earlier, it would have been with the older form that still had the global coordinates. The newer form version would have the local coordinates. I'm guessing that is why you saw this discrepancy as I have not changed the background data since that previous thread.

**Comment by ValentineHerr** [comment]
I think we can close this
