### ISSUE TITLE
assess FADs

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#76]
@djj4tree ,

Here's our current list of FADs:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/6355854/169378198-f149d1a2-d7d2-49e2-999d-ddb92768a406.png">

From a recent assessment by a student (thanks, @irdangler!) and from discussions in the field yesterday, these could use reassessment. 

Most notably, "Complete Defoliation" is true of any dead tree, and defoliation would be captured by % crown living, so I think that one should just be dropped. (@irdangler found that it was commonly but inconsistently reported for dead trees in our census.)

Most of the others could just use some clarification as to when they apply.

**Comment by djj4tree** [comment]
It obviously doesn't make sense to use this code for dead trees. The way we viewed complete defoliation is for alive unhealthy trees. We have an oak species that is often almost completely defoliated but still alive. This species isn't attacked by insects as far as we can tell but it is only epicormic sprouts. We also used this code for defoliation of eastern hemlock at Harvard Forest related to HWA.

**Comment by teixeirak** [comment]
Okay, so what's needed is to define each of these codes so that surveyors will apply them consistently. @emacmonigle , perhaps you could draft a list for our survey protocol based on the table above and what you learned in the field on Wednesday, highlighting any that don't make sense. We want this list to make sense to a new field surveyor, so you're a good person to judge. You can paste your draft list in this issue, and we can transfer to the guide once all questions are resolved.

**Comment by emacmonigle** [comment]
FAD Categories: 

U = Unable to determine

_Mechanical_
B= Broken stem (note cause, indicate level on tree)
CR= Crushed by other tree or tree parts
UP= Uprooted tree (root bole exposed) - **is bole the right word to use here? I think the bole is exposed when the tree is still standing. Maybe "root exposed" is sufficient.**
S= Slope failure (evident landslide even if small)
L= Lightning (tree splitting, straight scars from above)
Fi= Fire (stem charred, fire scars on bark)

_Biological Agents_
AN= Animal Damage (specify animal if possible) 
BB= Bark beetles present, beetle galleries. **Not sure about the overlap of BB and I, would BB be able to be used without the I tag? If not, we might want to collapse the category with I and make BB a subsection of I?** 
I= Insect infestation (e.g. EBA, other) **Mean EAB? Not sure if it stands for Emerald Ash Borer but I could be wrong. The VA Tree and forest health guide splits insect infestation into four categories: Sap suckers, defoliators, root/shoot/twig insects, and bark beetles. Could we make these four sub categories of this category, or make them four categories and collapse this one?**
DF= Complete defoliation ((record crown condition using Smith/Flower method below 1-5 scale). **Can probably remove, since captured in Crown intact and crown living**
F_V_ **Change tag for ease of use**= Fungi visible (give names if known) **Captures rust, rot, mats, and fruiting bodies. All identified cankers caused by fungus on plot. Does this mean cankers should 100% overlap with F? And if it does, does this need to be an outstanding category?**
K= Canker or swelling 
LF= Leaf damage (look for leaf spots, blotch, etc.) 
W= Wound **Maybe move to mechanical**
R= Rotting Stem **this sounds like a combination of W + F, so maybe it is already captured with those and this category could be removed. Also most rots are caused by fungi, so visible fungi can be captured by F**
R_D_ **change from R1 to RD** = Root damage **Was only used once in 2021, along with U, DF, and F. No way to assess root health visibly, and if roots are visual, this would be captured in UP. If it was a fungal root disease, would be captured in F. I think this category can be removed.**
R2= Armillaria Root disease ***type of fungus, can remove and be captured in Fungi visible with note of disease**

These are all recommendations on how we could change the categories. Let me know if these make sense and how we want to implement them!

**Comment by mageeluke** [comment]
@emacmonigle, hopefully this helps?


BB= Bark beetles present, beetle galleries. Not sure about the overlap of BB and I, would BB be able to be used without the I tag? If not, we might want to collapse the category with I and make BB a subsection of I?

**keep "BB"** 

I= Insect infestation (e.g. EBA, other) Mean EAB? Not sure if it stands for Emerald Ash Borer but I could be wrong. The VA Tree and forest health guide splits insect infestation into four categories: Sap suckers, defoliators, root/shoot/twig insects, and bark beetles. Could we make these four sub categories of this category, or make them four categories and collapse this one?

**keep "I"**


DF= Complete defoliation ((record crown condition using Smith/Flower method below 1-5 scale). Can probably remove, since captured in Crown intact and crown living

**keep "DF" it applies to many species: this is separate than leaf damage; it's where branches have died back, losing all leaves. Ash, for example, would have this at SCBI.** 

F_V_ Change tag for ease of use= Fungi visible (give names if known) Captures rust, rot, mats, and fruiting bodies. All identified cankers caused by fungus on plot. Does this mean cankers should 100% overlap with F? And if it does, does this need to be an outstanding category?

 **Fungi should be kept separate from cankers.** 

R= Rotting Stem this sounds like a combination of W + F, so maybe it is already captured with those and this category could be removed. Also most rots are caused by fungi, so visible fungi can be captured by F

Stems can rot in the absence of  wounds. "Fungi" is for fungi visible, obvious and external--keep "R"

R_D_ change from R1 to RD = Root damage Was only used once in 2021, along with U, DF, and F. No way to assess root health visibly, and if roots are visual, this would be captured in UP. If it was a fungal root disease, would be captured in F. I think this category can be removed.

**Root damage is indeed rare, but we coded it a few times. On slopes or near roads, it may be more pertinent.** 

R2= Armillaria Root disease *type of fungus, can remove and be captured in Fungi visible with note of disease

**Not used all that often, no need to remove though?** 

These are all recommendations on how we could change the categories. Let me know if these make sense and how we want to implement them!

**Comment by djj4tree** [comment]
Answers to @teixeirak Questions above

1. Bark beetles are of one family https://en.wikipedia.org/wiki/Bark_beetle ; EAB is of the wood boring family Buprestidae, so it probably should not be coded as a bark beetle.
2. The insect category contains a whole lot more than bark beetles. BB is a subgroup of I where greater knowledge of the causal agent is know. I would not require I if BB is selected because it seems redundant. 
3. Complete defoliation was interpreted by our group last year to mean that a portion (a major branch up to the whole tree) of the tree had been visibly completely defoliated. This term could use increased definition in the guides as it is somewhat misleading at first glance. something like Major Defoliation might be more accurate
4. There are plenty of fungi that do not make cankers but you may observe their fruiting body on the tree. That is what the fungi visible category is for. There are wood rotting fungi, for example, that do not cause any raised bark or external signs yet you might see a mushroom growing from a wound. We only coded fungi visible if we saw a fruiting body on the tree. Cankers can be dormant and have not sign of fungi besides the swelling in the bark or stem.
5. Wounds are any situation where the bark has been removed and wood is exposed to the air or soil.  Wounds and cankers are not mutually exclusive. There are canker causing fungi that infect wounds and keep a tree from healing over and we should code both wound and canker. Also, you can have a canker with not visible wood, so it get a canker code but no wound.
6.   I would code the top picture with all fungi. canker, and wound because I see exposed wood, fruiting bodies, and canker swelling.

**Comment by teixeirak** [comment]
Thanks @djj4tree , this is helpful! We'll work on an updated set of definitions for our census protocol and share.

**Comment by emacmonigle** [comment]
@teixeirak Yes, I'll work on that and have that done by today.

**Comment by emacmonigle** [comment]
FAD Catagories (2022):

**U** = Unable to determine cause of death

_Mechanical Damage_

**B** = Broken stem (note cause, indicate level on tree)
**CR** = Crushed by other tree or tree parts
**UP** = Uprooted Tree (root system exposed)
**S** = Slope faliure (evident landslide even if small)
**L** = Lightning (tree splitting, striaght scars from above)
**FI** = Fire (stem charred, fire scars on bark)

_Biological agents_

**AN** = Animal Damage (specify animal in notes if possible)
**BB** = Bark beetles present, beetle galleries (sub-catagory of I, inlcuding I not needed)
**I** = Insect infection (e.g. EAB)
**DF** = Complete defoliation of portion of stem (record crown condition using Smith/Flower method below 1-5 scale)
**F** = Fungi visible (includes fruiting mushroom bodies, fungal mats, and discoloration inside wounds or cankers)
**K** = Canker or swelling present 
**LF** = Leaf damage (Leaf spots, blotch, mildew, discoloration etc.)
**W** = Wound (not mutually exclusive with F or K)
**R** = Rotting stem
**R1** = Root damage
**R2** = Armillaria root disease (including F not needed)

Please let me know if these look good or if there's anything that needs to be changed.

I also had some further questions about classification:

1. If insect exit holes are present, would that go under I or BB? Do only bark beetles make these holes or are there other insects that could be the cause?

2. How might R be different from UP? What would each one look like and would they be mututally exclusive? 

3. If R2 is used, would I need to code for F and possibly W as well? Or would it already be captured?

**Comment by teixeirak** [comment]
Thaniis, @emacmonigle , and sorry for the slow response.

> I also had some further questions about classification:
> 
>     1. If insect exit holes are present, would that go under I or BB? Do only bark beetles make these holes or are there other insects that could be the cause?

**At SCBI, it would usually be I, as bark beetles in subfamily [Scolytinae](https://en.wikipedia.org/wiki/Bark_beetle) are not common (just elm bark beetles)**
> 
>     2. How might R be different from UP? What would each one look like and would they be mututally exclusive?

**R would apply to rot any place on the stem (e.g., a hollow/ soft spot), and the tree would often be standing. UP would apply in cases (including without any rot) where the tree has fallen over and the roots are exposed.**
> 
>     3. If R2 is used, would I need to code for F and possibly W as well? Or would it already be captured?

**Not necessary to include F if you get  R2. Record W only if you see exposed underlying tissue.**

**Comment by teixeirak** [comment]
I've added this improved set of defitions to the mortality protocol. I think we can close this now.
