### ISSUE TITLE
CI upload error

### ISSUE THREAD

**Issue by emacmonigle** [SCBI-ForestGEO/SCBImortality#91]
@jenajordan @jess-shue Hi, starting this in a new issue but was originally brought up in issue #90. I've run into another error today where when I downloaded the file from FF the file created two different excels, one from the Mortality 2022 and one from the Mortality 2022 stems removed form. I think uploading both excels separately would create an error.

Jess, would you be free anytime tomorrow to get on a call and try to sort this out?

**Comment by djj4tree** [comment]
@emacmonigle We are all synced from today's work.

**Comment by jenajordan** [comment]
@jess-shue @emacmonigle I could join a call tomorrow as well.  Should we be asking Albert / Valentine?

**Comment by teixeirak** [comment]
I think you'll need @ValentineHerr (although this might be quick and not require a call). Bert is on paternity leave, and we don't want to bother him. :-)

**Comment by emacmonigle** [comment]
Good point! @ValentineHerr do you know how we might fix this error? Also every other file that I've uploaded has given me an error so I feel like its an error from my side and a quick call would make sure I'm taking the right steps. Let me know if you have any ideas or if you'd be free to call.

**Comment by ValentineHerr** [comment]
@emacmonigle it is not your fault, it is because the file keeps changing in ways that break the code.....

Like now, where did the column "Crown position < 10 cm DBH" go? Was it dropped ? (I may have missed some of the conversations)

**Comment by emacmonigle** [comment]
I'm not sure in about the exported excel file. In FFF, the option still pops up on trees < 10 dbh and is filled out when necessary.

**Comment by ValentineHerr** [comment]
It is not the the EAB section anymore. It was until last commit @jenajordan. Did you accidentally remove that column ?

Before last commit:
![image](https://user-images.githubusercontent.com/19673377/181823574-41c40c97-1436-486b-bf68-53928f74e17f.png)

after last commit:

![image](https://user-images.githubusercontent.com/19673377/181823497-dbba6d6e-288a-45a5-be91-196f302ac2b3.png)

**Comment by jess-shue** [comment]
Hi @ValentineHerr, @emacmonigle, @jenajordan, @teixeirak 
Krista had asked that the <10 cm DBH trees were removed from the data to speed things up, and so that column was removed. This is why it is very difficult to change the form while we're in the midst of a census - I can add that column back in if it helps.

I've taken leave yesterday and today. I can pick this back up on Monday if that is OK.

**Comment by ValentineHerr** [comment]
oh, I see, thanks @jess-shue!
I think one problem with that is that data previously collected was lost, since we redownload the whole data each time.
So maybe when you come back from leave you can put that column back into the system but not making it required? (and hopefully the old data will reappear in next download . if not, we will find a solution).

**Comment by jess-shue** [comment]
@ValentineHerr Hmmm, that is strange. 
@emacmonigle and @jenajordan When you download the data from FFF's you should be able to filter by form. 
![image](https://user-images.githubusercontent.com/37407801/181825587-767b38bc-dd51-4ff6-b979-9a5d242fbd14.png)
It may be best to keep the previously collected data as a separate download because of the changes to the form, and download the data entered in the new form separately. 
I'll add the <10 cm crown position back in now.

**Comment by ValentineHerr** [comment]
> It may be best to keep the previously collected data as a separate download because of the changes to the form, and download the data entered in the new form separately.

Problem with that is that things get complicated code-wise. Needing to `rbind` files without the same sets of columns can cause problems. But maybe we are at a point where coding it would be better than making sure the FFF are complete.


> I'll add the <10 cm crown position back in now.
Thanks!

**Comment by jess-shue** [comment]
@ValentineHerr Got it. Well, the column has been restored, but having the two separate forms - with two different names - is still exporting the data into separate files, and has not restored that missing column because the data were collected on the previous version of the form without that column.

I can work to rbind the separate files and upload them if that would be helpful, but I won't be able to get to it until Monday...I'm heading to an appointment shortly.

**Comment by ValentineHerr** [comment]
oh shoot. Ok, no worries, we will figure that out on Monday

**Comment by jess-shue** [comment]
@ValentineHerr @emacmonigle @jenajordan 
Hi all, I think it would be best to go back to using the original 2022 form this week. My main purpose for creating a second form was to keep the original intact in case of an issue - last year we ran into trouble and I had issues backtracking in FFF's. I realize now that was not the correct way to do this!

@ValentineHerr If I create a file of the data from last week from the 'new' form, can we rbind it to the data each time a new set is uploaded via the R code? I'm thinking if we continue to use the 'old' form going forward, we can continue to download that data and upload it as before. By having a static file of last week's 'new' form data added to it prior to CI checks, would that be an OK solution?

**Comment by teixeirak** [comment]
@ValentineHerr , there have been a lot of messages in this repo that may be hard to track, but are a barrier to getting the CI working again, so I wanted to flag this. If I understand right, the next step would be for you to respond here.

**Comment by ValentineHerr** [comment]
Sorry about that.
@jess-shue, I am not sure I follow exactly. I'll rephrase here and let me know if I got it:
1. keep doing what has been done before: 
  a. In the field, @emacmonigle and @jenajordan keep working on the original 2022 form
  b. once back to the lab they download the whole data from that form (since day 1 of census) and push that to github, overwriting the previous file they pushed.
2. because we "messed-up" last week (by entering the data in the new form), the data from the new form only represents ~1week of work, which is missing in original 2022 form,:
  a. we need to keep that ~week of data in the raw data folder (it will ever change since we will start using the old form again)
  b. we need to always bring and merge that copy of that data in the script, so we have a complete record of the work and we can apply checks on it.

@jess-shue, If I understood correctly, please, go ahead and upload the latest of that "new form".

**Comment by jenajordan** [comment]
@jess-shue , @ValentineHerr , @teixeirak  - I will be on the forest plot tomorrow & Friday. Please confirm how I should do things/ what form to use. I will read back in the thread. Wondering why it still states only 25% complete (Dan's quads are not listed as done on map for example).

**Comment by jess-shue** [comment]
@ValentineHerr Yes, that all sounds like what I was trying to describe - thank you! I've added the file [here](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/raw_data/FFF_excel).

@jenajordan Please use the original form in FFF's - SCBI Mortality 2022.

**Comment by teixeirak** [comment]
From @mageeluke : "I used the most recent FastFields Form for all but three quads (two at the beginning). I used the “stems removed form” for the other three, which appear missing on the map (0426, 0428, 0331), but are completed."

I'm not sure how to handle this. Based on @ValentineHerr 's response above, I believe the solution is just to leave them and bring them in separately. Can someone else please confirm?

**Comment by jess-shue** [comment]
@teixeirak I believe we resolved this, the map is at 88% complete and I created a file for Valentine to incorporate from the other FFF's version. Everyone should be using the original SCBI Mortality 2022 FFF's. 

The quadrats Luke reported missing a showing on the map - was this from an older message?

**Comment by teixeirak** [comment]
Yeah, I was slow... Thanks for resolving it!

(And I think we can close this issue now.)

**Comment by jenajordan** [comment]
Just chiming in to say we are continuously using the original SCBI Mortality 2022 form. Just those few quads last week from Luke accidentally went into the other 'stem removed' form. Only 27 quads left!
